### PR TITLE
fix: preserve fetched text in targeted upskill mode

### LINKED ISSUE #1894: bug(upskill): --url-text URL path destroys the fetched JD via misused normalizeJd, then crashes with TypeError
## Problem

The **URL path** of upskill's targeted mode (`node upskill.mjs --url-text <url>`, #1739) is broken end-to-end on main: it destroys the extracted JD text and then crashes. The **file path** (`--url-text ./jds/x.txt`) works fine, which is probably why this hasn't been reported.

## Root cause — `upskill.mjs:607–610`

```js
try {
  const { normalizeJd } = await import('./browser-extract.mjs');
  targetText = normalizeJd(targetText, inputSource);
} catch (e) {}
```

`normalizeJd(raw, finalUrl)` (browser-extract.mjs) expects `raw` to be the **DOM-read object** `{ title, text }` — it's the shaper for browser-extract's own `readDom()` output. Here it's handed the **string** from `page.innerText('body')`. `raw?.title` and `raw?.text` on a string are `undefined`, so it returns:

```js
{ url: inputSource, title: '', text: '' }
```

Verified on main:

```
$ node -e "…normalizeJd('Senior Engineer role requiring Kubernetes and Go…','https://x/jd')…"
{"url":"https://x/jd","title":"","text":""}
```

Two failures stack:
1. **The fetched JD text is silently replaced by an empty object** — the Playwright/fetch work is thrown away.
2. `targetText` is now an object, so the downstream `computeTargetedGaps(targetText, …)` → `extractSkills(text)` → `text.matchAll(...)` throws **`TypeError: text.matchAll is not a function`** (verified). The empty `catch (e) {}` on 610 doesn't cover it — the throw happens later.

So for any real URL: successful navigation → destroyed text → crash. (Before the #1851 fix the same object flowed into the old suppression code — the URL path has been broken since the feature merged in #1796.)

## Fix

`page.innerText('body')` and `res.text()` already produce plain text — the shaper call is simply wrong here. Either:

- **(a) Delete lines 607–610.** The whitespace-collapsing/cap that `normalizeJd` would provide can be had honestly with `compactText(targetText)` (also exported by browser-extract.mjs), which is string-in/string-out; or
- **(b)** call it as designed: `targetText = normalizeJd({ text: targetText }, inputSource).text`.

(a) plus `compactText` is the minimal faithful fix.

## Test gap that let this ship

`runSelfTest()` covers extraction and (since #1851) the suppression fixture, but **nothing exercises the `--url-text` URL branch** — even a unit test asserting "the text reaching `computeTargetedGaps` is a non-empty string when the fetch returns text" would have caught this. Suggest adding exactly that (stub the text acquisition; no network needed).

Happy to PR the fix + test.

### PR DESCRIPTION
**Pull request by luochen211**
Closes #1894

## Summary
- compact URL-fetched JD text with the string-to-string browser extraction helper
- remove the normalizeJd call that converted body text into an empty object
- cover the URL text shape and downstream targeted gap extraction in the built-in self-test

## Tests
- `node upskill.mjs --self-test`
- `node test-all.mjs` (1738 passed, 0 failed; one expected missing-user-CV warning)

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved skill extraction from job descriptions fetched through URLs.
  * Preserved the expected text format during processing, helping ensure extracted job description content remains usable.
  * Added validation to confirm URL-based extraction returns meaningful text and identifies expected skills reliably.

* **Tests**
  * Expanded automated checks for URL-fetched job description processing and skill extraction.

### CODE REVIEW

**Comment by santifer** [comment]
Closing with credit, @luochen211: #1917 just landed for #1894. Yours was first by about an hour and the diagnosis was identical; the tiebreak went to the issue author's fix for being the more surgical of the two (no new exported surface, keeps the dynamic-import fallback). Appreciated as always: your allocator work in #1910 already made today's changelog.
